services:
  back:
    build: ./backend/django
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    volumes:
      - back_media:/backend/media
      - back_static:/backend/static
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    restart: unless-stopped

  db:
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  back_media:
  back_static:
